### ISSUE TITLE
[error] unsupported OS "ubuntu"

### ISSUE THREAD

**Issue by stnolting** [ghdl/setup-ghdl#13]
Since today ago I get this error:

![Image](https://github.com/user-attachments/assets/ae32e4ff-399b-44ef-8f03-804c64d3cee0)

This is my GitHub Actions config:

```
    - name: '📦 Install GHDL'
      uses: ghdl/setup-ghdl@v1
      with:
        version: nightly
        backend: mcode
```

I am using `ubuntu-latest` (= Ubuntu 24.04) which should be supported, right? 🤔
